####################################################################################################
# Atomonova CentOS Serpens Dockerfile - Mon May 23 03:05:42 PDT 2022 - v.0.0.9
# Centos 7 is the last major release supported by RedHat. Support ends in 2024.
# CentOS Serpens may be replaced with another distribution depending on RedHat/CentOS developments.
####################################################################################################

FROM centos:centos7.9.2009
# 75.15 MB


####################################################################################################
# Show OS details.
RUN cat /etc/centos-release
# CentOS Linux release 7.9.2009 (Core)
RUN cat /proc/version
# Linux version 5.10.104-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203,
# GNU ld (GNU Binutils) 2.35.2) #1 SMP Thu Mar 17 17:08:06 UTC 2022


RUN yum --assumeyes update
# TODO: Consider  - shall we lock versions? Is the best way just to freeze an image once it is all
# worked out in the Dockerfile? Probably so. Impossible to lock versions on everything in updates.

# Updated:
#   bash.x86_64 0:4.2.46-35.el7_9                             bind-license.noarch 32:9.11.4-26.P2.el7_9.9
#   binutils.x86_64 0:2.27-44.base.el7_9.1                    ca-certificates.noarch 0:2021.2.50-72.el7_9
#   centos-release.x86_64 0:7-9.2009.1.el7.centos             coreutils.x86_64 0:8.22-24.el7_9.2
#   curl.x86_64 0:7.29.0-59.el7_9.1                           cyrus-sasl-lib.x86_64 0:2.1.26-24.el7_9
#   device-mapper.x86_64 7:1.02.170-6.el7_9.5                 device-mapper-libs.x86_64 7:1.02.170-6.el7_9.5
#   expat.x86_64 0:2.1.0-14.el7_9                             glib2.x86_64 0:2.56.1-9.el7_9
#   glibc.x86_64 0:2.17-326.el7_9                             glibc-common.x86_64 0:2.17-326.el7_9
#   gzip.x86_64 0:1.5-11.el7_9                                kpartx.x86_64 0:0.4.9-135.el7_9
#   krb5-libs.x86_64 0:1.15.1-51.el7_9                        libblkid.x86_64 0:2.23.2-65.el7_9.1
#   libcurl.x86_64 0:7.29.0-59.el7_9.1                        libmount.x86_64 0:2.23.2-65.el7_9.1
#   libsmartcols.x86_64 0:2.23.2-65.el7_9.1                   libuuid.x86_64 0:2.23.2-65.el7_9.1
#   libxml2.x86_64 0:2.9.1-6.el7_9.6                          libxml2-python.x86_64 0:2.9.1-6.el7_9.6
#   nspr.x86_64 0:4.32.0-1.el7_9                              nss.x86_64 0:3.67.0-4.el7_9
#   nss-softokn.x86_64 0:3.67.0-3.el7_9                       nss-softokn-freebl.x86_64 0:3.67.0-3.el7_9
#   nss-sysinit.x86_64 0:3.67.0-4.el7_9                       nss-tools.x86_64 0:3.67.0-4.el7_9
#   nss-util.x86_64 0:3.67.0-1.el7_9                          openldap.x86_64 0:2.4.44-25.el7_9
#   openssl-libs.x86_64 1:1.0.2k-25.el7_9                     python.x86_64 0:2.7.5-90.el7
#   python-libs.x86_64 0:2.7.5-90.el7                         rpm.x86_64 0:4.11.3-48.el7_9
#   rpm-build-libs.x86_64 0:4.11.3-48.el7_9                   rpm-libs.x86_64 0:4.11.3-48.el7_9
#   rpm-python.x86_64 0:4.11.3-48.el7_9                       systemd.x86_64 0:219-78.el7_9.5
#   systemd-libs.x86_64 0:219-78.el7_9.5                      tzdata.noarch 0:2022a-1.el7
#   util-linux.x86_64 0:2.23.2-65.el7_9.1                     vim-minimal.x86_64 2:7.4.629-8.el7_9
# TODO: Measure size delta. No obvious way except do a before/after. The update download is said to be 52 MB.







####################################################################################################
# Install basic tools for working in the shell.
####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################




####################################################################################################



##
#

